import path from 'node:path'

// Local file names and remote paths originate from the device (or from the
// renderer) and must never be allowed to escape the directory they are meant
// for. These helpers are pure so they can be unit tested without Electron.

const MAX_NAME_BYTES = 255

/**
 * Reduce an untrusted name to a single safe path component. Throws if nothing
 * usable remains, so callers fail loudly instead of writing somewhere odd.
 */
export function safeFileName(name: unknown): string {
  if (typeof name !== 'string') throw new Error('Invalid file name')
  if (name.includes('\0')) throw new Error('Invalid file name')
  // Take the last component of either separator style, then drop traversal
  const last = name.split(/[\\/]/).filter(Boolean).pop() ?? ''
  if (last === '' || last === '.' || last === '..') throw new Error(`Invalid file name: ${JSON.stringify(name)}`)
  if (Buffer.byteLength(last) > MAX_NAME_BYTES) throw new Error('File name is too long')
  return last
}

/** True if `child` resolves to `parent` or something inside it. */
export function isInside(parent: string, child: string): boolean {
  const rel = path.relative(path.resolve(parent), path.resolve(child))
  return rel === '' || (!rel.startsWith('..') && !path.isAbsolute(rel))
}

/** Join an untrusted file name onto a trusted directory, guaranteeing containment. */
export function joinInside(dir: string, name: unknown): string {
  const resolved = path.join(dir, safeFileName(name))
  if (!isInside(dir, resolved)) throw new Error('Path escapes destination directory')
  return resolved
}

/** Remote (device) paths are POSIX, absolute and NUL-free. */
export function assertRemotePath(value: unknown): string {
  if (typeof value !== 'string' || value.length === 0 || value.length > 4096) throw new Error('Invalid remote path')
  if (value.includes('\0')) throw new Error('Invalid remote path')
  if (!value.startsWith('/')) throw new Error('Remote path must be absolute')
  return value
}

export function assertLocalPath(value: unknown): string {
  if (typeof value !== 'string' || value.length === 0 || value.length > 4096) throw new Error('Invalid local path')
  if (value.includes('\0')) throw new Error('Invalid local path')
  if (!path.isAbsolute(value)) throw new Error('Local path must be absolute')
  return value
}

/** Transfer / operation ids are generated by the renderer; keep them filename-safe. */
export function assertOperationId(value: unknown): string {
  if (typeof value !== 'string' || !/^[A-Za-z0-9_-]{1,64}$/.test(value)) throw new Error('Invalid operation id')
  return value
}

/** Parent directory of a POSIX path ('/a/b' -> '/a', '/a' -> '/'). */
export function posixDir(p: string): string {
  const trimmed = p.replace(/\/+$/, '')
  const idx = trimmed.lastIndexOf('/')
  return idx <= 0 ? '/' : trimmed.slice(0, idx)
}

export function posixBase(p: string): string {
  return p.replace(/\/+$/, '').split('/').pop() ?? ''
}

const PROTECTED_REMOTE = new Set(['/', '/sdcard', '/storage', '/storage/emulated', '/storage/emulated/0', '/data', '/system', '/mnt', '/mnt/sdcard'])

/** Roots that destructive operations must refuse outright (delete/move). */
export function isProtectedRemotePath(p: string): boolean {
  const norm = '/' + p.split('/').filter(s => s !== '' && s !== '.').join('/')
  return PROTECTED_REMOTE.has(norm) || norm.split('/').includes('..')
}
